code --install-extension AdamCaviness.theme-monokai-dark-soda
code --install-extension bhurt.puppet-snippets
code --install-extension DavidAnson.vscode-markdownlint
code --install-extension DotJoshJohnson.xml
code --install-extension formulahendry.code-runner
code --install-extension idleberg.hopscotch
code --install-extension janjoerke.jenkins-pipeline-linter-connector
code --install-extension jpogran.puppet-vscode
code --install-extension marlon407.code-groovy
code --install-extension ms-azuretools.vscode-azureappservice
code --install-extension ms-azuretools.vscode-docker
code --install-extension ms-mssql.mssql
code --install-extension ms-python.python
code --install-extension ms-vscode-remote.remote-wsl
code --install-extension ms-vscode.azure-account
code --install-extension ms-vscode.csharp
code --install-extension ms-vscode.powershell
code --install-extension redhat.java
code --install-extension redhat.vscode-yaml
code --install-extension secanis.jenkinsfile-support
code --install-extension tht13.html-preview-vscode
code --install-extension VisualStudioExptTeam.vscodeintellicode
code --install-extension vscjava.vscode-java-debug
code --install-extension vscjava.vscode-java-dependency
code --install-extension vscjava.vscode-java-pack
code --install-extension vscjava.vscode-java-test
code --install-extension vscjava.vscode-maven
code --install-extension vscode-icons-team.vscode-icons
code --install-extension vscoss.vscode-ansible
code --install-extension yzhang.markdown-all-in-one